package juanda;

import org.omg.CORBA.PRIVATE_MEMBER;

public class Fibonacci {
	public static void main(String[] args) {

		/*
		 * Each new term in the Fibonacci sequence is generated by adding the previous
		 * two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * 
		 * By considering the terms in the Fibonacci sequence whose values do not exceed
		 * four million, find the sum of the even-valued terms.
		 */
//
//	Cada nuevo
//	termino en
//	la serie
//	fibonacci es
//	generado sumando los 2
//	ultimos terminos, iniciando con 1 y 2,los 10
//	primeros terminos serian*
//	1,2,3,5,8,13,21,34,55,89,...
//
//	considerando los
//	valores en
//	la serie
//	fibonacci cuyos
//	valores no exceden 4 millones,
//	encuentra la
//	suma de
//	los valores pares.
		int i = 0;
		int a = 1;
		int b = 2;
		int sumaPares = 2;
		boolean pares = false;

		while (i < 10) {
			i = a + b;
			pares = numeroPares(i);
			a = b;
			b = i;
			System.out.println("serie fibonacci : " + i);
			if (pares) {
				sumaPares += i;
			}
		}
		System.out.println("suma pares: " + sumaPares);
	}

	private static boolean numeroPares(int i) {
		int par = 0;
		par = i % 2;
		if (par == 0) {
			return true;
		}
		return false;
	}
}
//	while(true) {
//		
//	}
//	
//	do {
//		
//	}while(true);
//}
