package practice;

public class Fibonacci {

	public static void main(String[] args) {
		System.out.println("La suma de los numeros pares de la serie fibonacci hasta el rango 4000000 es: "
				+ sumaFibonacciPares(4000000));
	}

	/*
	 * Each new term in the Fibonacci sequence is generated by adding the previous
	 * two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * 
	 * By considering the terms in the Fibonacci sequence whose values do not exceed
	 * four million, find the sum of the even-valued terms.
	 */
	public static long sumaFibonacciPares(int range) {
		int a = 1;
		int b = 1;
		long sum = 0L;
		while (b < range) {
			int pivote = a + b;
			a = b;
			b = pivote;
			if (pivote % 2 == 0) {
				sum += pivote;
			}
		}
		return sum;
	}

}
